steps:
- id: 'build docker image'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build -t gcr.io/coinos-326717/github.com/tokenocean/nftglee:staging .'
  images: ['gcr.io/coinos-326717/github.com/tokenocean/nftglee:staging']

- id: 'deploy to k8s'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      kubectl patch deployment nftglee-staging -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"
